### ISSUE TITLE
rust sample exits with seg fault

### ISSUE THREAD

**Issue by syllabix** [getditto/samples#127] opened 2023-09-12 18:36 UTC
Hello all! Firstly - thank you for preparing these examples. They have been super useful in understanding how to use the SDK and Ditto end - to - end. 

I have been running into an issue trying to get the rust sample to work. I have done the following to generate the error

1. Configured a playground account on ditto.live
2. Cloned this project from `main`
3. Ran the example project with `cargo run --release -- --app-id <app id> --shared-token <playground token> --collection my-collection`

The program exits with `Segmentation fault: 11` 

I get the following logs from the `Ditto::builder` the first time I run the program
```
[INFO] 2023-09-12T18:26:47.679Z: ; database_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_store"; attachments_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_attachments"; replication_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_replication"; tempfile_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_tempfile"
[DEBUG] 2023-09-12T18:26:48.114Z: AuthClient: Searching Store for CachedSiteInfo
[DEBUG] 2023-09-12T18:26:48.114Z: AuthClient: CACHED_SITE_INFO_KEY not found in storage
[DEBUG] 2023-09-12T18:26:48.114Z: AuthClient: CachedSiteInfo is missing a SiteId, invalidating auth
[DEBUG] 2023-09-12T18:26:48.115Z: AuthClient: CachedSiteInfo is missing a peer key, invalidating auth
[DEBUG] 2023-09-12T18:26:48.115Z: AuthClient: storing to cache; req = SiteInfo
Segmentation fault: 11
```
When running the program again without cleaning the target dir I get the following repeatedly:
```
[INFO] 2023-09-12T18:28:45.443Z: ; database_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_store"; attachments_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_attachments"; replication_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_replication"; tempfile_dir = "/Users/syllabix/dittolive/samples/rs/target/release/ditto_tempfile"
[DEBUG] 2023-09-12T18:28:45.887Z: AuthClient: Searching Store for CachedSiteInfo
[DEBUG] 2023-09-12T18:28:45.890Z: AuthClient: found CachedSiteInfo
[INFO] 2023-09-12T18:28:45.890Z: AuthClient: using cached SiteId; site_id = 16906052078113615490
[INFO] 2023-09-12T18:28:45.892Z: AuthClient: no token, authentication needed immediately
[DEBUG] 2023-09-12T18:28:45.893Z: AuthClient: no x509 certificate present
[WARN] 2023-09-12T18:28:45.893Z: AuthClient: No valid Web token present. Cannot request certificate.
Segmentation fault: 11
```

Development Environment Specs:
Rust Compiler
`rustc 1.72.0 (5680fa18f 2023-08-23)`

Cargo Dependencies
```toml
dittolive-ditto = "=4.1.1"
dittolive-ditto-sys = "=4.1.1"
structopt = "0.3.26"
serde_json = "1.0"
```

OS
`macOS 13.4`
`x86_64-apple-darwin`

( Pardon in advance if this issue is a result of user error 😅 )

**Comment by okdistribute** [comment] 2023-09-12 19:51
Can you try again on Ditto 4.4.0?

Thanks for reporting.

**Comment by syllabix** [comment] 2023-09-13 16:45
I moved both `ditto` and `ditto-sys` to `4.4.0` but I am still getting the seg faults. 

When stepping through with the debugger the crash occurs in the `ffi_sdk::ditto_make` invocation in builder.rs (line 151)
as this starts to move into `unsafe` territory - is it possible my compiler configuration is incorrect?

**Comment by okdistribute** [comment] 2024-01-12 15:51
Sorry you ran into this. Can you try Rust version 1.66.1?

**Comment by nicholastmosher** [comment] 2024-06-24 15:49
Thanks for reporting this issue! I believe this was caused by the mismatch between the Ditto SDK version being used and the Rust toolchain used to compile it. I've recently updated [the Compatibility Maps documentation for the Rust SDK](https://docs.ditto.live/compatibility/rust) which shows that for SDK version `4.1.1`, you'll need to be using Rust version `1.66.1` as @okdistribute mentioned above.

Additionally, the sample application has been [moved to a new repository](https://github.com/getditto/template-rust/blob/main/src/bin/simple_querybuilder.rs) where it has been updated to the latest SDK version.

I'm going to close this issue as it's now addressed by the compatibility maps page. Please feel free to open new issues in the future if you run into any more problems!

**Closed by nicholastmosher** 2024-06-24 15:49 UTC
