### ISSUE TITLE
Android TODO app crashes on orientation change

### ISSUE THREAD

**Issue by abunur** [getditto/samples#103] opened 2023-04-13 15:05 UTC
Steps to reproduce:

- launch or debug the app
- rotate the device
- app crashes

Stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: live.dittolive.todo, PID: 4570
    java.lang.RuntimeException: Unable to start activity ComponentInfo{live.dittolive.todo/com.dittolive.todo.MainActivity}: java.lang.RuntimeException: Ditto Identity could not be created: File already locked, working dir = /data/user/0/live.dittolive.todo/files/ditto/ditto_auth, retried 50 times
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3641)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5779)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5670)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7884)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.RuntimeException: Ditto Identity could not be created: File already locked, working dir = /data/user/0/live.dittolive.todo/files/ditto/ditto_auth, retried 50 times
        at live.ditto.DittoIdentity.throwAuthClientCreationError(DittoIdentity.kt:221)
        at live.ditto.DittoIdentity$OnlinePlayground.<init>(DittoIdentity.kt:138)
        at com.dittolive.todo.MainActivity.onCreate(MainActivity.kt:57)
        at android.app.Activity.performCreate(Activity.java:8341)
        at android.app.Activity.performCreate(Activity.java:8320)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3778) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5779) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5670) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7884) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by anyercastillo** [comment] 2023-10-29 21:48
Cannot reproduce it on https://github.com/getditto/template-app-jetpack-compose-kotlin-todo/

Please let me know if I should test on a different project.

**Comment by okdistribute** [comment] 2023-10-30 00:45
Great let's close this then, thanks for taking a look.

**Closed by okdistribute** 2023-10-30 00:45 UTC
Labels: bug, android
